version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "api:app"]
